numpy

In [2]:
import numpy as np
# 1D array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
# 2D array
b = np.array([[1, 2],
              [3, 4]])
print(b)


[[1 2]
 [3 4]]


In [4]:
# 3D array
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print(c)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
import numpy as np
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])
b = np.array([[1, 1, 1],
              [1, 1, 2],
              [1, 1, 2]])
print(a + b)

[[2 1 1]
 [2 2 3]
 [3 1 2]]


In [7]:
print(a - b)

[[ 0 -1 -1]
 [ 0  0 -1]
 [ 1 -1 -2]]


In [8]:
print(a * b)

[[1 0 0]
 [1 1 2]
 [2 0 0]]


In [9]:
print(a / b)

[[1.  0.  0. ]
 [1.  1.  0.5]
 [2.  0.  0. ]]


In [10]:
import numpy as np
a = np.array([[1, 0, 0],
              [1, 1, 1],
              [2, 0, 0]])
print(np.max(a))

2


In [11]:
print(np.min(a))

0


In [12]:
print(np.average(a))

0.6666666666666666


pandas

In [13]:
import pandas as pd

In [14]:
df= pd.read_csv('weather_data.csv')
df.head()

YEAR  DOY    RF    WS     RH  ...  ALLSKY_H     PS  ALLSKY_TOA  ALLSKY_RF     TS
0  1990    1  0.00  2.61  74.97  ...     15.70  99.21       31.93      35.68  27.08
1  1990    2  0.00  3.41  71.62  ...     15.88  99.22       31.97      34.85  26.66
2  1990    3  0.00  3.63  70.04  ...     17.60  99.30       32.00      35.50  26.02
3  1990    4  0.01  3.64  70.81  ...     14.94  99.42       32.04      35.64  25.58
4  1990    5  0.49  3.92  77.22  ...      6.48  99.49       32.11      35.10  24.18

[5 rows x 13 columns]

In [15]:
df.head(10)

YEAR  DOY    RF    WS     RH  ...  ALLSKY_H     PS  ALLSKY_TOA  ALLSKY_RF     TS
0  1990    1  0.00  2.61  74.97  ...     15.70  99.21       31.93      35.68  27.08
1  1990    2  0.00  3.41  71.62  ...     15.88  99.22       31.97      34.85  26.66
2  1990    3  0.00  3.63  70.04  ...     17.60  99.30       32.00      35.50  26.02
3  1990    4  0.01  3.64  70.81  ...     14.94  99.42       32.04      35.64  25.58
4  1990    5  0.49  3.92  77.22  ...      6.48  99.49       32.11      35.10  24.18
5  1990    6  8.07  4.11  86.94  ...      6.19  99.38       32.15      36.50  24.02
6  1990    7  9.27  3.62  82.68  ...      6.91  99.40       32.18      36.32  25.69
7  1990    8  7.33  2.96  82.19  ...      6.34  99.50       32.26      35.89  25.53
8  1990    9  1.36  3.89  80.26  ...     11.52  99.45       32.29      35.46  25.63
9  1990   10  0.14  3.53  75.28  ...     17.57  99.44       32.36      33.84  25.37

[10 rows x 13 columns]

In [16]:
df.tail()

YEAR  DOY    RF    WS  ...     PS  ALLSKY_TOA  ALLSKY_RF     TS
11512  2021  190  2.32  4.71  ...  98.73       36.42      37.65  26.42
11513  2021  191  4.08  6.15  ...  98.76       36.44      39.05  25.30
11514  2021  192  0.76  5.34  ...  98.76       36.45      37.10  25.83
11515  2021  193  3.00  4.93  ...  98.75       36.47      37.12  26.30
11516  2021  194  0.48  4.79  ...  98.78       36.48      36.34  25.97

[5 rows x 13 columns]

In [17]:
df.describe()

YEAR           DOY  ...     ALLSKY_RF            TS
count  11517.000000  11517.000000  ...  11517.000000  11517.000000
mean    2005.270209    181.686898  ...     35.739435     27.158148
std        9.105071    105.383817  ...      1.531764      2.377533
min     1990.000000      1.000000  ...     28.680000     21.170000
25%     1997.000000     90.000000  ...     35.140000     25.450000
50%     2005.000000    180.000000  ...     36.040000     26.690000
75%     2013.000000    273.000000  ...     36.690000     28.570000
max     2021.000000    366.000000  ...     40.610000     35.100000

[8 rows x 13 columns]

In [25]:
df['YEAR']

0        1990
1        1990
2        1990
3        1990
4        1990
         ... 
11512    2021
11513    2021
11514    2021
11515    2021
11516    2021
Name: YEAR, Length: 11517, dtype: int64

In [21]:
df.YEAR

0        1990
1        1990
2        1990
3        1990
4        1990
         ... 
11512    2021
11513    2021
11514    2021
11515    2021
11516    2021
Name: YEAR, Length: 11517, dtype: int64

In [27]:
df['rain'] = False
df.head()

YEAR  DOY    RF    WS     RH  ...     PS  ALLSKY_TOA  ALLSKY_RF     TS   rain
0  1990    1  0.00  2.61  74.97  ...  99.21       31.93      35.68  27.08  False
1  1990    2  0.00  3.41  71.62  ...  99.22       31.97      34.85  26.66  False
2  1990    3  0.00  3.63  70.04  ...  99.30       32.00      35.50  26.02  False
3  1990    4  0.01  3.64  70.81  ...  99.42       32.04      35.64  25.58  False
4  1990    5  0.49  3.92  77.22  ...  99.49       32.11      35.10  24.18  False

[5 rows x 14 columns]

In [30]:
df.drop('rain',inplace=True, axis=1)
df.head()

YEAR  DOY    RF    WS     RH  ...  ALLSKY_H     PS  ALLSKY_TOA  ALLSKY_RF     TS
0  1990    1  0.00  2.61  74.97  ...     15.70  99.21       31.93      35.68  27.08
1  1990    2  0.00  3.41  71.62  ...     15.88  99.22       31.97      34.85  26.66
2  1990    3  0.00  3.63  70.04  ...     17.60  99.30       32.00      35.50  26.02
3  1990    4  0.01  3.64  70.81  ...     14.94  99.42       32.04      35.64  25.58
4  1990    5  0.49  3.92  77.22  ...      6.48  99.49       32.11      35.10  24.18

[5 rows x 13 columns]